// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusFine.Infrastructure.Data;

#nullable disable

namespace NexusFine.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409041318_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexusFine.Core.Entities.Appeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ApplicantPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FineId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByOfficerId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FineId")
                        .IsUnique();

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.ToTable("Appeals");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EntityType");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HeadOfficerBadge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Lilongwe Traffic",
                            Zone = "Lilongwe"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Blantyre Traffic",
                            Zone = "Blantyre"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Mzuzu Traffic",
                            Zone = "Mzuzu"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Zomba Traffic",
                            Zone = "Zomba"
                        });
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Fine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DriverLicenceNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("DriverNationalId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DriverPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvidencePhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OffenceCodeId")
                        .HasColumnType("int");

                    b.Property<int>("OfficerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PenaltyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleColour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleModel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DriverNationalId");

                    b.HasIndex("IssuedAt");

                    b.HasIndex("OffenceCodeId");

                    b.HasIndex("OfficerId");

                    b.HasIndex("PlateNumber");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Fines");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.OffenceCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("DefaultFineAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("OffenceCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "OC-001",
                            DefaultFineAmount = 50000m,
                            Description = "Exceeding the posted speed limit",
                            IsActive = true,
                            Name = "Speeding"
                        },
                        new
                        {
                            Id = 2,
                            Code = "OC-002",
                            DefaultFineAmount = 75000m,
                            Description = "Failure to stop at a red traffic light",
                            IsActive = true,
                            Name = "Red Light Violation"
                        },
                        new
                        {
                            Id = 3,
                            Code = "OC-003",
                            DefaultFineAmount = 25000m,
                            Description = "Driver or passenger not wearing seatbelt",
                            IsActive = true,
                            Name = "No Seatbelt"
                        },
                        new
                        {
                            Id = 4,
                            Code = "OC-004",
                            DefaultFineAmount = 40000m,
                            Description = "Driving with an expired road licence",
                            IsActive = true,
                            Name = "Expired Road Licence"
                        },
                        new
                        {
                            Id = 5,
                            Code = "OC-005",
                            DefaultFineAmount = 60000m,
                            Description = "Operating a vehicle in an unroadworthy condition",
                            IsActive = true,
                            Name = "Unroadworthy Vehicle"
                        },
                        new
                        {
                            Id = 6,
                            Code = "OC-006",
                            DefaultFineAmount = 30000m,
                            Description = "Driving in the wrong lane",
                            IsActive = true,
                            Name = "Wrong Lane"
                        },
                        new
                        {
                            Id = 7,
                            Code = "OC-007",
                            DefaultFineAmount = 20000m,
                            Description = "Motorcycle rider without a helmet",
                            IsActive = true,
                            Name = "No Helmet"
                        },
                        new
                        {
                            Id = 8,
                            Code = "OC-008",
                            DefaultFineAmount = 80000m,
                            Description = "Vehicle carrying load exceeding permitted weight",
                            IsActive = true,
                            Name = "Overloading"
                        },
                        new
                        {
                            Id = 9,
                            Code = "OC-009",
                            DefaultFineAmount = 100000m,
                            Description = "Operating a vehicle without a valid licence",
                            IsActive = true,
                            Name = "Driving Without Licence"
                        },
                        new
                        {
                            Id = 10,
                            Code = "OC-010",
                            DefaultFineAmount = 50000m,
                            Description = "Using a handheld mobile phone while driving",
                            IsActive = true,
                            Name = "Use of Mobile Phone While Driving"
                        });
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Officer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DeviceImei")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastKnownLocation")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<double?>("LastLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("LastLongitude")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NfcTagId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BadgeNumber")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("NfcTagId");

                    b.ToTable("Officers");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FineId")
                        .HasColumnType("int");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InitiatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FineId");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TransactionReference");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Appeal", b =>
                {
                    b.HasOne("NexusFine.Core.Entities.Fine", "Fine")
                        .WithOne("Appeal")
                        .HasForeignKey("NexusFine.Core.Entities.Appeal", "FineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fine");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Fine", b =>
                {
                    b.HasOne("NexusFine.Core.Entities.Department", "Department")
                        .WithMany("Fines")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusFine.Core.Entities.OffenceCode", "OffenceCode")
                        .WithMany("Fines")
                        .HasForeignKey("OffenceCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusFine.Core.Entities.Officer", "Officer")
                        .WithMany("Fines")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("OffenceCode");

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Officer", b =>
                {
                    b.HasOne("NexusFine.Core.Entities.Department", "Department")
                        .WithMany("Officers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Payment", b =>
                {
                    b.HasOne("NexusFine.Core.Entities.Fine", "Fine")
                        .WithMany("Payments")
                        .HasForeignKey("FineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fine");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Department", b =>
                {
                    b.Navigation("Fines");

                    b.Navigation("Officers");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Fine", b =>
                {
                    b.Navigation("Appeal");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.OffenceCode", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Officer", b =>
                {
                    b.Navigation("Fines");
                });
#pragma warning restore 612, 618
        }
    }
}
