// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusFine.Infrastructure.Data;

#nullable disable

namespace NexusFine.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427193411_Module35_DistrictsAndRegion")]
    partial class Module35_DistrictsAndRegion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexusFine.Core.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OfficerId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("OfficerId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Appeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ApplicantPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FineId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByOfficerId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FineId")
                        .IsUnique();

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.ToTable("Appeals");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EntityType");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HeadOfficerBadge")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Region");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Lilongwe Traffic",
                            Region = "Central",
                            Zone = "Lilongwe"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Blantyre Traffic",
                            Region = "Southern",
                            Zone = "Blantyre"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Mzuzu Traffic",
                            Region = "Northern",
                            Zone = "Mzimba"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Zomba Traffic",
                            Region = "Southern",
                            Zone = "Zomba"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Chitipa Traffic",
                            Region = "Northern",
                            Zone = "Chitipa"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Karonga Traffic",
                            Region = "Northern",
                            Zone = "Karonga"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Likoma Traffic",
                            Region = "Northern",
                            Zone = "Likoma"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Nkhata Bay Traffic",
                            Region = "Northern",
                            Zone = "Nkhata Bay"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Rumphi Traffic",
                            Region = "Northern",
                            Zone = "Rumphi"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Dedza Traffic",
                            Region = "Central",
                            Zone = "Dedza"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "Dowa Traffic",
                            Region = "Central",
                            Zone = "Dowa"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "Kasungu Traffic",
                            Region = "Central",
                            Zone = "Kasungu"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "Mchinji Traffic",
                            Region = "Central",
                            Zone = "Mchinji"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "Nkhotakota Traffic",
                            Region = "Central",
                            Zone = "Nkhotakota"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "Ntcheu Traffic",
                            Region = "Central",
                            Zone = "Ntcheu"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Name = "Ntchisi Traffic",
                            Region = "Central",
                            Zone = "Ntchisi"
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            Name = "Salima Traffic",
                            Region = "Central",
                            Zone = "Salima"
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            Name = "Balaka Traffic",
                            Region = "Southern",
                            Zone = "Balaka"
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            Name = "Chikwawa Traffic",
                            Region = "Southern",
                            Zone = "Chikwawa"
                        },
                        new
                        {
                            Id = 20,
                            IsActive = true,
                            Name = "Chiradzulu Traffic",
                            Region = "Southern",
                            Zone = "Chiradzulu"
                        },
                        new
                        {
                            Id = 21,
                            IsActive = true,
                            Name = "Machinga Traffic",
                            Region = "Southern",
                            Zone = "Machinga"
                        },
                        new
                        {
                            Id = 22,
                            IsActive = true,
                            Name = "Mangochi Traffic",
                            Region = "Southern",
                            Zone = "Mangochi"
                        },
                        new
                        {
                            Id = 23,
                            IsActive = true,
                            Name = "Mulanje Traffic",
                            Region = "Southern",
                            Zone = "Mulanje"
                        },
                        new
                        {
                            Id = 24,
                            IsActive = true,
                            Name = "Mwanza Traffic",
                            Region = "Southern",
                            Zone = "Mwanza"
                        },
                        new
                        {
                            Id = 25,
                            IsActive = true,
                            Name = "Neno Traffic",
                            Region = "Southern",
                            Zone = "Neno"
                        },
                        new
                        {
                            Id = 26,
                            IsActive = true,
                            Name = "Nsanje Traffic",
                            Region = "Southern",
                            Zone = "Nsanje"
                        },
                        new
                        {
                            Id = 27,
                            IsActive = true,
                            Name = "Phalombe Traffic",
                            Region = "Southern",
                            Zone = "Phalombe"
                        },
                        new
                        {
                            Id = 28,
                            IsActive = true,
                            Name = "Thyolo Traffic",
                            Region = "Southern",
                            Zone = "Thyolo"
                        });
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentOfficerId")
                        .HasColumnType("int");

                    b.Property<string>("Imei")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("PairedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurrentOfficerId");

                    b.HasIndex("Serial")
                        .IsUnique();

                    b.HasIndex("StationId");

                    b.HasIndex("Status");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Fine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DriverLicenceNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("DriverNationalId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DriverPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvidencePhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OffenceCodeId")
                        .HasColumnType("int");

                    b.Property<int>("OfficerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PenaltyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleColour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleModel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DriverNationalId");

                    b.HasIndex("IssuedAt");

                    b.HasIndex("OffenceCodeId");

                    b.HasIndex("OfficerId");

                    b.HasIndex("PlateNumber");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Fines");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.OffenceCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("DefaultFineAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("OffenceCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "OC-001",
                            DefaultFineAmount = 50000m,
                            Description = "Exceeding the posted speed limit",
                            IsActive = true,
                            Name = "Speeding"
                        },
                        new
                        {
                            Id = 2,
                            Code = "OC-002",
                            DefaultFineAmount = 75000m,
                            Description = "Failure to stop at a red traffic light",
                            IsActive = true,
                            Name = "Red Light Violation"
                        },
                        new
                        {
                            Id = 3,
                            Code = "OC-003",
                            DefaultFineAmount = 25000m,
                            Description = "Driver or passenger not wearing seatbelt",
                            IsActive = true,
                            Name = "No Seatbelt"
                        },
                        new
                        {
                            Id = 4,
                            Code = "OC-004",
                            DefaultFineAmount = 40000m,
                            Description = "Driving with an expired road licence",
                            IsActive = true,
                            Name = "Expired Road Licence"
                        },
                        new
                        {
                            Id = 5,
                            Code = "OC-005",
                            DefaultFineAmount = 60000m,
                            Description = "Operating a vehicle in an unroadworthy condition",
                            IsActive = true,
                            Name = "Unroadworthy Vehicle"
                        },
                        new
                        {
                            Id = 6,
                            Code = "OC-006",
                            DefaultFineAmount = 30000m,
                            Description = "Driving in the wrong lane",
                            IsActive = true,
                            Name = "Wrong Lane"
                        },
                        new
                        {
                            Id = 7,
                            Code = "OC-007",
                            DefaultFineAmount = 20000m,
                            Description = "Motorcycle rider without a helmet",
                            IsActive = true,
                            Name = "No Helmet"
                        },
                        new
                        {
                            Id = 8,
                            Code = "OC-008",
                            DefaultFineAmount = 80000m,
                            Description = "Vehicle carrying load exceeding permitted weight",
                            IsActive = true,
                            Name = "Overloading"
                        },
                        new
                        {
                            Id = 9,
                            Code = "OC-009",
                            DefaultFineAmount = 100000m,
                            Description = "Operating a vehicle without a valid licence",
                            IsActive = true,
                            Name = "Driving Without Licence"
                        },
                        new
                        {
                            Id = 10,
                            Code = "OC-010",
                            DefaultFineAmount = 50000m,
                            Description = "Using a handheld mobile phone while driving",
                            IsActive = true,
                            Name = "Use of Mobile Phone While Driving"
                        });
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Officer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DeviceImei")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastKnownLocation")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<double?>("LastLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("LastLongitude")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NfcTagId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PrimaryPatrolPostId")
                        .HasColumnType("int");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BadgeNumber")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("NfcTagId");

                    b.HasIndex("PrimaryPatrolPostId");

                    b.HasIndex("StationId");

                    b.ToTable("Officers");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.PatrolPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Lng")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("StationId");

                    b.ToTable("PatrolPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PP-LIL-018-A",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Kamuzu Hwy North",
                            StationId = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Code = "PP-LIL-018-B",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Kamuzu Hwy South",
                            StationId = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Code = "PP-LIL-001-A",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Area 18 Roundabout",
                            StationId = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Code = "PP-BLT-001-A",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Limbe Market Junction",
                            StationId = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Code = "PP-MZU-001-A",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Mzuzu Bus Depot",
                            StationId = 4,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Code = "PP-ZBA-001-A",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Zomba M3 Junction",
                            StationId = 5,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FineId")
                        .HasColumnType("int");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InitiatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FineId");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TransactionReference");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ConsecutiveFailedSyncs")
                        .HasColumnType("int");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Lng")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("OfficerInChargeBadge")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PhysicalAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StationServerEndpoint")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StationServerPublicKey")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Zone");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "STN-LIL-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 750 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            IsActive = true,
                            Name = "Area 18 Police Station",
                            PhysicalAddress = "Area 18, Lilongwe",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Lilongwe"
                        },
                        new
                        {
                            Id = 2,
                            Code = "STN-LIL-002",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 750 200",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            IsActive = true,
                            Name = "Kamuzu Highway Checkpoint",
                            PhysicalAddress = "M1 Kamuzu Highway, North",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Lilongwe"
                        },
                        new
                        {
                            Id = 3,
                            Code = "STN-BLT-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 840 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            IsActive = true,
                            Name = "Limbe Police Station",
                            PhysicalAddress = "Limbe, Blantyre",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Blantyre"
                        },
                        new
                        {
                            Id = 4,
                            Code = "STN-MZU-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 332 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            IsActive = true,
                            Name = "Mzuzu Central Police Station",
                            PhysicalAddress = "Mzuzu CBD",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Mzimba"
                        },
                        new
                        {
                            Id = 5,
                            Code = "STN-ZBA-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 525 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            IsActive = true,
                            Name = "Zomba Police Station",
                            PhysicalAddress = "Zomba CBD",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Zomba"
                        },
                        new
                        {
                            Id = 6,
                            Code = "STN-CHI-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 382 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            IsActive = true,
                            Name = "Chitipa Police Station",
                            PhysicalAddress = "Chitipa Boma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Chitipa"
                        },
                        new
                        {
                            Id = 7,
                            Code = "STN-KAR-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 362 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 6,
                            IsActive = true,
                            Name = "Karonga Police Station",
                            PhysicalAddress = "Karonga Boma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Karonga"
                        },
                        new
                        {
                            Id = 8,
                            Code = "STN-LIK-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 374 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 7,
                            IsActive = true,
                            Name = "Likoma Island Police Post",
                            PhysicalAddress = "Chizumulu Harbour",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Likoma"
                        },
                        new
                        {
                            Id = 9,
                            Code = "STN-NKB-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 352 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 8,
                            IsActive = true,
                            Name = "Nkhata Bay Police Station",
                            PhysicalAddress = "Nkhata Bay Boma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Nkhata Bay"
                        },
                        new
                        {
                            Id = 10,
                            Code = "STN-RUM-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 372 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 9,
                            IsActive = true,
                            Name = "Rumphi Police Station",
                            PhysicalAddress = "Rumphi Boma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Rumphi"
                        },
                        new
                        {
                            Id = 11,
                            Code = "STN-DED-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 223 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 10,
                            IsActive = true,
                            Name = "Dedza Police Station",
                            PhysicalAddress = "Dedza Boma, M1",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Dedza"
                        },
                        new
                        {
                            Id = 12,
                            Code = "STN-DOW-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 282 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 11,
                            IsActive = true,
                            Name = "Dowa Police Station",
                            PhysicalAddress = "Dowa Boma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Dowa"
                        },
                        new
                        {
                            Id = 13,
                            Code = "STN-KAS-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 253 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 12,
                            IsActive = true,
                            Name = "Kasungu Police Station",
                            PhysicalAddress = "Kasungu Boma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Kasungu"
                        },
                        new
                        {
                            Id = 14,
                            Code = "STN-MCH-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 242 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 13,
                            IsActive = true,
                            Name = "Mchinji Border Police Station",
                            PhysicalAddress = "Mchinji Border (Zambia)",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Mchinji"
                        },
                        new
                        {
                            Id = 15,
                            Code = "STN-NKK-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 292 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 14,
                            IsActive = true,
                            Name = "Nkhotakota Police Station",
                            PhysicalAddress = "Nkhotakota Boma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Nkhotakota"
                        },
                        new
                        {
                            Id = 16,
                            Code = "STN-NTC-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 235 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 15,
                            IsActive = true,
                            Name = "Ntcheu Police Station",
                            PhysicalAddress = "Ntcheu Boma, M1",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Ntcheu"
                        },
                        new
                        {
                            Id = 17,
                            Code = "STN-NTI-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 295 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 16,
                            IsActive = true,
                            Name = "Ntchisi Police Station",
                            PhysicalAddress = "Ntchisi Boma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Ntchisi"
                        },
                        new
                        {
                            Id = 18,
                            Code = "STN-SAL-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 263 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 17,
                            IsActive = true,
                            Name = "Salima Police Station",
                            PhysicalAddress = "Salima Boma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Salima"
                        },
                        new
                        {
                            Id = 19,
                            Code = "STN-BAL-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 552 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 18,
                            IsActive = true,
                            Name = "Balaka Police Station",
                            PhysicalAddress = "Balaka Boma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Balaka"
                        },
                        new
                        {
                            Id = 20,
                            Code = "STN-CHK-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 422 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 19,
                            IsActive = true,
                            Name = "Chikwawa Police Station",
                            PhysicalAddress = "Chikwawa Boma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Chikwawa"
                        },
                        new
                        {
                            Id = 21,
                            Code = "STN-CHZ-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 462 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 20,
                            IsActive = true,
                            Name = "Chiradzulu Police Station",
                            PhysicalAddress = "Chiradzulu Boma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Chiradzulu"
                        },
                        new
                        {
                            Id = 22,
                            Code = "STN-MAC-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 535 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 21,
                            IsActive = true,
                            Name = "Machinga Police Station",
                            PhysicalAddress = "Liwonde Boma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Machinga"
                        },
                        new
                        {
                            Id = 23,
                            Code = "STN-MAN-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 584 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 22,
                            IsActive = true,
                            Name = "Mangochi Police Station",
                            PhysicalAddress = "Mangochi Boma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Mangochi"
                        },
                        new
                        {
                            Id = 24,
                            Code = "STN-MUL-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 466 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 23,
                            IsActive = true,
                            Name = "Mulanje Police Station",
                            PhysicalAddress = "Mulanje Boma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Mulanje"
                        },
                        new
                        {
                            Id = 25,
                            Code = "STN-MWA-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 432 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 24,
                            IsActive = true,
                            Name = "Mwanza Border Police Station",
                            PhysicalAddress = "Mwanza Border (Mozambique)",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Mwanza"
                        },
                        new
                        {
                            Id = 26,
                            Code = "STN-NEN-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 433 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 25,
                            IsActive = true,
                            Name = "Neno Police Station",
                            PhysicalAddress = "Neno Boma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Neno"
                        },
                        new
                        {
                            Id = 27,
                            Code = "STN-NSA-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 451 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 26,
                            IsActive = true,
                            Name = "Nsanje Police Station",
                            PhysicalAddress = "Nsanje Boma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Nsanje"
                        },
                        new
                        {
                            Id = 28,
                            Code = "STN-PHA-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 467 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 27,
                            IsActive = true,
                            Name = "Phalombe Police Station",
                            PhysicalAddress = "Phalombe Boma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Phalombe"
                        },
                        new
                        {
                            Id = 29,
                            Code = "STN-THY-001",
                            ConsecutiveFailedSyncs = 0,
                            ContactPhone = "+265 1 473 100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 28,
                            IsActive = true,
                            Name = "Thyolo Police Station",
                            PhysicalAddress = "Thyolo Boma",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Zone = "Thyolo"
                        });
                });

            modelBuilder.Entity("NexusFine.Core.Entities.AppUser", b =>
                {
                    b.HasOne("NexusFine.Core.Entities.Officer", "Officer")
                        .WithMany()
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Appeal", b =>
                {
                    b.HasOne("NexusFine.Core.Entities.Fine", "Fine")
                        .WithOne("Appeal")
                        .HasForeignKey("NexusFine.Core.Entities.Appeal", "FineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fine");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Device", b =>
                {
                    b.HasOne("NexusFine.Core.Entities.Officer", "CurrentOfficer")
                        .WithMany()
                        .HasForeignKey("CurrentOfficerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NexusFine.Core.Entities.Station", "Station")
                        .WithMany("Devices")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentOfficer");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Fine", b =>
                {
                    b.HasOne("NexusFine.Core.Entities.Department", "Department")
                        .WithMany("Fines")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusFine.Core.Entities.OffenceCode", "OffenceCode")
                        .WithMany("Fines")
                        .HasForeignKey("OffenceCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusFine.Core.Entities.Officer", "Officer")
                        .WithMany("Fines")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("OffenceCode");

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Officer", b =>
                {
                    b.HasOne("NexusFine.Core.Entities.Department", "Department")
                        .WithMany("Officers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusFine.Core.Entities.PatrolPost", "PrimaryPatrolPost")
                        .WithMany()
                        .HasForeignKey("PrimaryPatrolPostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NexusFine.Core.Entities.Station", "Station")
                        .WithMany("Officers")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("PrimaryPatrolPost");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.PatrolPost", b =>
                {
                    b.HasOne("NexusFine.Core.Entities.Station", "Station")
                        .WithMany("PatrolPosts")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Payment", b =>
                {
                    b.HasOne("NexusFine.Core.Entities.Fine", "Fine")
                        .WithMany("Payments")
                        .HasForeignKey("FineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fine");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Station", b =>
                {
                    b.HasOne("NexusFine.Core.Entities.Department", "Department")
                        .WithMany("Stations")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Department", b =>
                {
                    b.Navigation("Fines");

                    b.Navigation("Officers");

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Fine", b =>
                {
                    b.Navigation("Appeal");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.OffenceCode", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Officer", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("NexusFine.Core.Entities.Station", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Officers");

                    b.Navigation("PatrolPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
